### PR TITLE
Fix lineheight style to line-height

### PR DESCRIPTION
**Pull request by paulwellnerbou**
Thank you for this extension!
Here is the pull request to fix the line height.

### CODE REVIEW

**Comment by 1beb** [comment]
I actually tried this before and it works. But if you notice on the hover
colour on the working files is now only half the word vertically and I
found that more distracting/ugly then having a squishy display. Not sure
which CSS element is controlling this tho.

**Comment by paulwellnerbou** [comment]
I prefer the higher line-width, but I'll keep trying. "lineheight", without dash, is not support to work, regardless of the value.

Unfortunately, just scaling the whole body (which looks ok) breaks the UI interaction, this would be the best solution.

```
    ExtensionUtils.addEmbeddedStyleSheet("body {"+
   "-webkit-transform: scale(1.2);"+
   "-webkit-transform-origin: 0% 0%;"+
"}");
```

**Comment by paulwellnerbou** [comment]
I added some more css stuff, it looks ok now on my screen.
Maybe you can double check.

**Comment by 1beb** [comment]
Good work finding those selectors. Thanks for PR. Merged and pushed to extension registry.

**Comment by paulwellnerbou** [comment]
Great, thank you.
That's not hard work, F12 opens Chrome's web developer view for Brackets.

**Pull request merged**
